title: 汉字自动拆分系统
description: 一种现代的方法
themeConfig:
  sidebar:
    - title: 概述
      path: /
    - title: 用户文档
      path: /user/
    - title: 开发者文档
      path: /developer/
      collapsable: false
      children:
        - /developer/base
        - /developer/core
        - /developer/preset
        - /developer/cache
        - /developer/util
plugins:
  - ['@maginapp/vuepress-plugin-katex', {delimiters: dollars}]
